### ISSUE TITLE
neon 3D conv and pooling layers do not instantiate properly

### ISSUE THREAD

**Issue by caseus-viridis** [svalleco/3Dgan#1]
The link to the code with our 3D GAN:
https://github.com/svalleco/3Dgan/blob/master/neon/gan3D.py
 
Concerning the errors: for example, 
https://github.com/svalleco/3Dgan/blob/master/neon/gan3D.py#L57
also next 2 lines are wrong too. It doesn't work in 3D case, but as you said GAN model with 3D Conv/Deconv layers has not been put up yet.

The error messege:
```
Traceback (most recent call last):
  File "GAN.py", line 51, in <module>
    Deconv((6, 6, 8, 64), **conv4),
  File "//anaconda/envs/neon/lib/python3.6/site-packages/neon-2.0.0-py3.6.egg/neon/layers/layer.py", line 1655, in __init__
    dilation=dilation, init=init, bsum=batch_norm))
  File "//anaconda/envs/neon/lib/python3.6/site-packages/neon-2.0.0-py3.6.egg/neon/layers/layer.py", line 950, in __init__
    self.deconvparams.update(d)
TypeError: cannot convert dictionary update sequence element #0 to a sequence
```

And some problems with types. If I remove dilation, padding parameters or put only one number, it works, but it isn't what we need. In the discriminator case, it seems to work, but in fact, it works in 2d not 3d.  

Besides, for example, the Poling layer isn't implemented for 3D too 
https://github.com/NervanaSystems/neon/blob/master/neon/layers/layer.py#L493
We need the polling layer for the discriminator  :)

Thank you for your attention and participation!

Best,
Elena.

**Comment by caseus-viridis** [comment]
Hi Elena,

See below for a fix of the problem.  Tested with neon 2.0.0. 

Summary:
- For the problem with `Conv`, changed constructor arguments `dilation`, `padding` and `stride` from tuple/list to dict.  
- For the problem with `Pooling`, cannot reproduce with neon 2.0.0.  As far as this example is concerned, 3D pooling layer instantiated without an error.  

Follow-up thoughts:
- If you find the 3D `Conv` API unsatisfactory in this fix, please create an issue on the neon repo, we will try our best to address it and improve in future releases.  Thanks!

As I do not have write access to this repo, I cannot generate a PR.  Here is a fix of the problem in diff against commit `46cc923`:
```
diff --git a/neon/gan3D.py b/neon/gan3D.py
index 9e21232..3c18149 100644
--- a/neon/gan3D.py
+++ b/neon/gan3D.py
@@ -1,3 +1,7 @@
+#!/usr/bin/env python
+"""
+A GAN using 3D conv layers
+"""
 import os
 from datetime import datetime
 from neon.callbacks.callbacks import Callbacks, GANCostCallback
@@ -41,7 +45,7 @@ D_layers = [Conv((5, 5, 5, 32), **conv1),
             Conv((5, 5, 5, 8), **conv3),
             Dropout(keep = 0.8),
 
-            #Pooling((2, 2, 2)),
+            Pooling((2, 2, 2)),
             # what's about the Flatten Layer?
             Linear(1, init=init)] #what's about the activation function?
 
@@ -49,14 +53,14 @@ D_layers = [Conv((5, 5, 5, 32), **conv1),
 # generator using covolution layers
 latent_size = 200
 relu = Rectlin(slope=0)  # relu for generator
-conv4 = dict(init=init, batch_norm=True, activation=lrelu, dilation=[2, 2, 2])
-conv5 = dict(init=init, batch_norm=True, activation=lrelu, padding=[2, 2, 0], dilation=[2, 2, 3])
-conv6 = dict(init=init, batch_norm=False, activation=lrelu, padding=[1, 0, 3])
+conv4 = dict(init=init, batch_norm=True, activation=lrelu, dilation=dict(dil_h=2, dil_w=2, dil_d=2))
+conv5 = dict(init=init, batch_norm=True, activation=lrelu, padding=dict(pad_h=2, pad_w=2, pad_d=0), dilation=dict(dil_h=2, dil_w=2, dil_d=3))
+conv6 = dict(init=init, batch_norm=False, activation=lrelu, padding=dict(pad_h=1, pad_w=0, pad_d=3))
 G_layers = [Linear(64 * 7 * 7, init=init), # what's about the input volume
-            Reshape((7, 7, 8, 8)), 
+            Reshape((7, 7, 8, 8)),
             Conv((6, 6, 8, 64), **conv4),
             Conv((6, 5, 8, 6), **conv5),
-            Conv((3, 3, 8, 6), **conv6), 
+            Conv((3, 3, 8, 6), **conv6),
             Conv((2, 2, 2, 1), init=init, batch_norm=False, activation=relu)]
             # what's about Embedding
 
@@ -65,6 +69,3 @@ layers = GenerativeAdversarial(generator=Sequential(G_layers, name="Generator"),
 
 # setup cost function as CrossEntropy
 cost = GeneralizedGANCost(costfunc=GANCost(func="modified"))
-
-
-
```

Best,
Xin
